### ISSUE TITLE
Review Web Manager Position Descriptions for requirements (Skills, Competencies, Training)

### ISSUE THREAD

**Issue by gailsprinkle** [GSA/EDX#113]
- [x] Develop a roster of website managers from the Touchpoints survey
- [x] Identify PDs of each website manager
- [x] [Fix Roster with lessons learned from survey and review new PDs](https://github.com/GSA/EDX/issues/113#issuecomment-1059581758)
- [x] Determine the number of unique PDs (and standardized PDs vs. specific PDs)
- [x] Pull a sample of PDs 
- [x] Review PDs for requirements (skills, competencies, training)
- [x] Identify opportunities to include requirements 

How can we elevate the role of the website manager so 1) that role is clearly identified & delinated 2) site managers have the required skills & competencies 3) site managers are held accountable to be in compliance with all regulations?

In Issue 55, we reviewed a sample of site manager PDs and found that none of them addressed skills, competencies, regulations, or any requirements pertaining to website management compliance. After consultation with Classification, we decided to review the PDs of every site manager to determine the 1) series 2) bargaining unit status 3) skills, competencies required 4) regulations. We'll analyze that information and make a recommendation if site manager PDs should include certain requirements. We'll continue to collaborate with Classification and consult with Labor Relations.

**Comment by ryanwoldatwork** [comment]
Is there an existing framework for how HR approaches all this? Titles/Positions/People/Responsibilities/Roles/Tasks?

In the past, I've worked on Workflow systems where tasks have be specified explicitly, and those tasks can be assigned to different roles, based on responsibilities, which are based on position descriptions + other duties as assigned.

The point being: if work is modeled, it can be reported on in greater detail, and managed more flexibly.

**Comment by gailsprinkle** [comment]
@ryanwoldatwork The trend in position descriptions to to standardize them so that they are more general and less specific. The performance plan, updated at least annually, can be more specific.

**Comment by gailsprinkle** [comment]
@monicas-d and Gail identified 92 GSA website managers via Touchpoints Website Inventory. (There are also contractors listed). We reviewed 39 PDs (42% of the total) across series (301, 343, 1101, 2210) to search for requirements around website management skills/competencies, adherence to specific web management regulations, or training. 

Of the PDs reviewed, no series consistently required web management skills (2210 came the closest), and none consistently required compliance to specifc regulations or training. 

Conclusion: PDs are often standardized and are not often updated. PDs are probably not the place to require web skills, compliance, or training.

Recommendation: Move foward to explore strategies to add web skills, compliance, and/or training to web manager performance plans. 
Dependencies: Adding digital stewardship to HSSO performance plans.

**Comment by monicas-d** [comment]
Closing this and adding a card for putting these in performance plans (unless a card already exists for that? I will check). Thanks!

**Comment by monicas-d** [comment]
Reopening after discussion with Mike Seymour and Labor Relations:

Performance Mgmt (Mike Seymour):
- If you're going to update perf plans, you need to update PDs first BUT ONLY for those website managers who do not already have mention of website manager in it (or some version thereof); for those, you can update just performance plans

Labor Relations (Sue Scheider, Paula Lucak, and Casandra Loggins-Mitchell):
- When changing performance requirements, currently LR has to notify NFFE; but that may change in the next three months or so
- Will they have to recompete their jobs if we update their PDs (answer: it depends and we need to get details from classification AND determine the language we want to include)
- There are a significant number of bargaining unit employees on website manager inventory roster (FYI)

Next steps:

1. Find out from the team - what is the definition we will use for a website manager? @ryanwoldatwork @RachelF @mvogelgesang @anatecture @hatfieldjm4 @AKM399 
2. Monica/Gail to meet with Classification again and 1-share the website manager definition AND 2-determine if there is a percentage of time that employee has to perform the duty in order to be added to his/her/their PD (grade change?) 3-what impact if any does adding language have on the classification? Title? Grade? Series? Training requirement? Certification?)
3. Monica/Gail to meet with Chiefs of Staff to discuss plan moving forward to find out WHO is actually a website manager based on the inventory / roster we have (i.e. some of the people on our roster are SES and likely they are not the website manager).

**Comment by gailsprinkle** [comment]
@monicas-d  & Gail met with Charlotte Watson - CP-C, Manuela Martinez - CRFE 11/17/21
We suggested language for Website Manager PDs: "Ensures program websites (or digital properties) are compliant with current GSA policies, guidelines, and federal regulations".
Charlotte says that language sounds fine to her: what is the skill set around that around knowledge and skills for that? We need a skill set for Factor 1.
Need some pen/ink change that needs to be done to elaborate around that language
Who all is on that same PD? Classifier will need to look who is on the PD. We need to know NAMES of who is on that PD
We have to be careful not to impose requirements on people who are on the same PD but do not have website mgr roles

Next Steps: @monicas-d Please review these next steps and edit as appropriate:

- [ ] Define a website manager @anatecture @RachelF 
- [ ] Reach out to Chiefs of Staff with website manager description and their roster from the Website Inventory
- [ ] Ask them to validate roster with their staff
- [ ] Produce validated GSA website Manager roster
- [ ] Identify PDs for each validated website manager
- [ ] Sort out those PDs without any language pertaining to website management
- [ ] Work with Classification to determine next steps

**Comment by monicas-d** [comment]
Looks good as of now. Things could be revised as we go along with this process in terms of next steps. Thank you!

**Comment by ryanwoldatwork** [comment]
Related to https://github.com/GSA/EDX/issues/113#issuecomment-955010624,

For consideration, https://reader.elsevier.com/reader/sd/pii/S1877050919305198

This diagram depicts some of the common objects to represent the domain or HR systems.

<img width="804" alt="Screen Shot 2021-11-17 at 11 43 17 AM" src="https://user-images.githubusercontent.com/64987852/142271479-ce317059-f455-4876-a9c1-a271bcef1d9c.png">

The more such data is accurately modeled and managed, the greater capabilities the organization will have to model, simulate, manage, and report on.

> HR-Ontology provides  a  knowledge  base,  offer  possibility  to  query  each  role  according  to  their  competencies,  authority  etc,  and  to  query  each process according  to  the  assigned  role,  the  necessary  T&T  and  the  needed artifacts. Second, the proposed ontology can be exploited as a reliable tool to develop decision support systems...

**Comment by AKM399** [comment]
@gailsprinkle I would love to talk more about the data model @ryanwoldatwork has here and how it might assist in the mix/match/and matrixing approach to the PD that @RachelF described in the last meeting.  @RachelF in our next meeting I'll discuss the item with you as i think this might be a matter of stringing several good ideas people have together.

**Comment by anatecture** [comment]
[Building Website Managers for PDs Workshop Series](https://docs.google.com/document/d/1O4HyalKdqqVFtPuY3i2C8hdVu0jGOqeQ5LzxzgBu5j4/edit#) write up: 

Defining Website Managers to Build PDs
Background: 
The attributes for website managers listed below came out of a three workshop series by the Enterprise Digital Experience Team in December 2021. 

Workshop Methodology: 
Workshop was designed by Ana Monroe (EDX), applying the Paper Doll workshop framework. The workshop used a [digital whiteboard](https://www.figma.com/file/8Da4QI2kwYAelC1wEhxRNZ/Defining-Website-Managers-to-Build-PDs?node-id=30%3A606) to collect participants’ thoughts and serve as a discussion platform. The format was: 

- Brainstorm attributes: Write down as many attributes of a website manager that you can think of.    
- Sort attributes: Sort attributes into one of three categories: Core, Supporting-Must Have, or Supporting Nice-to-Have. Core attributes focus on the individual knowing how and who to ask for information on tasks and topics. Supporting attributes focus on the individual knowing how to perform specific tasks and/or be specialists in specific topics. 
- Core attributes are attributes all website managers must have to achieve the website manager role. These attributes are not unique to any one position but are common across any role that includes website management in it. 
- Supporting- Must Have attributes are not key portions of a website manager’s role, but ones that they must understand or know in order to be an effective website manager. 
- Supporting-Nice-to-Have attributes are attributes that will distinguish candidates from one another in any website manager role, but are not required to be an effective website manager.  
- Build managers: Match three attributes to make a website manager. Build as many as you can. Note: this portion of the workshop changed shape in-flight. We centered on sorting attributes into themes required by PDs, so as to hand off a set of attributes most useful to HR Specialists penning boilerplate PDs, instead of Hiring Managers tailoring PDs. Hiring Manager-centered attribute organization might be a useful addition to this work.  
- Translation: PD: How might this team now, at the end of this workshop, help Gail and Monica to translate this work into PDs or PD-ready language? Note: the attributes from this workshop series are not uniformly PD-ready, but we can help HR edit the wording of attributes where needed. 

Purpose: 
The purpose of this workshop series was to outline for HR the necessary attributes of a GSA website manager. These attributes should be considered a kit from which Hiring Managers and HR Specialists are able to build position descriptions. These position descriptions are by necessity similar to each other but not identical, reflective of the needs of each unique team and role.  

Participants: 
The following people were involved: 
Monica Suber-Duffy (HR)
Gail Sprinkle (HR) 
Ryan Wold (TTS) 
Ana Monroe (OCE) 
Aaron Meyers (OGP)
Jonah Hatfield (GSA IT) 

Themes and attributes
Job basics 
Note: To be a job basic, the item needs to be in their resume; to be a something else, they need to be able to tell a story about it in their interview 
Core: 
Has a good understanding of the subject matter on their site 
Does not think pdfs on the internet are good enough
Supporting-Must Have
Understands the basics of information architecture
Skilled content editor
Proficient in customer journey mapping
Understands that UX and content writing are different things but are related 
Leadership basics
Core
Person most empowered to make decisions that keep the website compliant with the policy and law
understands that the internet is the primary place we do business at GSA
Acts as an advocate for customers
the person who best articulates the websites point
they give the technical direction for website work
can cooordinate an effective content management strategy
Works with a customer to determine the appropriate content to put on a website to achieve its goals
they can answer most questions in the DLP and/or website inventory
Understands that a website is a tool to serve customers
Coalition-Building
Core
Can work with a team to do all of the web things
communicate in plain language
understands that digital is a task held in common
Can ask somebody for help
Participates in GSA/gov-wide digital communities of practice
Can coordinate with other humans (above and below) in the organization 
Supporting-Must Have
Is comfortable with shared and digital communications and backlogs
Governance
Understands that engineers are not just people to make the things they say they want, but are people who solve problems they don’t even know exist
attend necessary meetings/governance networks - 508 and others
Technical competencies
Core
Understands SEO enough to work with others
Understands how to write for the web
Has a basic understanding of HTML
Knows, broadly, what a CMS is
Content editor-in-chief
Understands what DAP means
Supporting Must Have
has worked with designers or design shops
treats a website like a Product™️
Web analytics
User experience design
understands web analytics (basic traffic and origins of traffic)
Supporting Nice-to-Have
understands advanced web analytics (events, funnels, cohorts)
Can update a Federalist website
Proficient in using analytics to track activity trends on the site (Is it being used in the intended way?)
Knows how style sheets work
Compliance
Core
Understands the importance of 508 compliance
knows what the US web design system is
Is familiar with the US Web Design System (USWDS)
Business acumen
Core
Understands a website is not a brochure: understands that this is a buisiness tool; site must have som ebusiness value
Customer Experience
Supporting Must Have
Contract management
Can work with somebody in GSA regarding budgeting aspects
Can build a content strategy
Fundamental competency: public service motivation
Supporting Must Have: 
Wants to manage a website - has a desire to
Supporting Nice-to-Have
bias towards learning

**Comment by anatecture** [comment]
> @monicas-d & Gail met with Charlotte Watson - CP-C, Manuela Martinez - CRFE 11/17/21 We suggested language for Website Manager PDs: "Ensures program websites (or digital properties) are compliant with current GSA policies, guidelines, and federal regulations". Charlotte says that language sounds fine to her: what is the skill set around that around knowledge and skills for that? We need a skill set for Factor 1. Need some pen/ink change that needs to be done to elaborate around that language Who all is on that same PD? Classifier will need to look who is on the PD. We need to know NAMES of who is on that PD We have to be careful not to impose requirements on people who are on the same PD but do not have website mgr roles
> 
> Next Steps: @monicas-d Please review these next steps and edit as appropriate:
> 
> * [x]  Define a website manager @anatecture @RachelF
> * [ ]  Reach out to Chiefs of Staff with website manager description and their roster from the Website Inventory
> * [ ]  Ask them to validate roster with their staff
> * [ ]  Produce validated GSA website Manager roster
> * [ ]  Identify PDs for each validated website manager
> * [ ]  Sort out those PDs without any language pertaining to website management
> * [ ]  Work with Classification to determine next steps

where are we with this list @monicas-d @gailsprinkle? Anything we can check off or discard?

**Comment by monicas-d** [comment]
@anatecture  - @gailsprinkle and I are going to meet next week when she's back to discuss next steps. Thanks for your patience!

**Comment by gailsprinkle** [comment]
Next steps:
Consult with Classification on the Themes and Attributes of website managers. Discuss the best approach to work with Chiefs of Staff in identifying website managers in their organizations and how best to modify PDs if necessary.

**Comment by anatecture** [comment]
This next step makes sense to me @gailsprinkle - closing this issue.

**Comment by gailsprinkle** [comment]
@monicas-d  & @gailsprinkle met with Classification (Charlotte Watson & Manuela Martinez) on 3/2/2022.  If employees spends less than 25% of time in the role, then adding the requirements isn't necessary. If more than 25%,  requirements may be added. If over 75%, a new PD might need to be written. Then Staffing needs to get involved to see if the employee qualifies for the position.
New PDs may be created for new hires.
Next Steps:

- [ ] Define the language that will help identify the web manager population.
@monicas-d FACTOR 1 DRAFT: **"Knowledge of the USWDS (United States Web Design System) Principles, Guidance, and/or Code. Skilled in one or more of the following: accessibility, content management, customer experience, digital design, information architecture, search engine optimization, user experience, USWDS coding."**

Pilot a process to identify web managers & their supervisors with the Chief of Staff of one organization. 
- [ ] Ask CoS to validate the web manager roster with supervisors, using the new description (above) and the Inventory roster.
- [ ] Produce a validated GSA website Manager/Supervisor roster for that organization.
- [ ] Pull and review PDs of each web manager to determine how much applicable language is used.
- [ ] Interview supervisors to determine the percentage of time web managers spend in the role. Note if their duties or KSA requirements are listed in the PD.
- [ ] For employees who spend <25% on web management, note if there is any applicable language in the PD. Determine if action is required.
- [ ] For employees who spend 25% to 75%, review PD, and determine if action is required.
- [ ] For employees who spend >75%, review PD, and determine if action is required.
- [ ] Meet with Staffing, Classification, and Performance to determine next steps.

Incorporate learning, and initiate across GSA.

- [ ] Define a GSA web manager roster and follow HR procedures to include language in PDs when appropriate, and create new PDs when necessary. 

The next step would be to offer language to supervisors to add to performance plans according to % of time spent in the role.

**Comment by anatecture** [comment]
All listed items in this issue are complete.
