### ISSUE TITLE
CX CoP Jan 11 slide deck - Intro to Change & Transition Management

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#136]
Sheev asked Gail / Monica to present to the CX Community of Practice in January about the importance of change management. 

We have drafted a deck and it is done once Sheev / Ana approve it.

List below the specific actions to be taken:

- Draft the deck (done!)
- Sheev / Monica / Gail to meet to discuss deck
- Sheev / Ana to approve deck

https://docs.google.com/presentation/d/1n6O1P6Yvo4w4Qz2vPc2JpHrnlipIoZPFu61oxcOo6zw/edit#slide=id.p

**Comment by anatecture** [comment]
I like where this deck is going, suggest that you start with EDX, since it's an in-flight, large-scale, and very new change management project, and it specifically what brought you to the CX CoP today. 

Don't shy away from talking about the changes you all have had to make to your working style (github being a very large example), and how you reacted to those changes. Talk about your wins (brining multiple offices into a single Crucial Conversations class springs to mind; using HCD interviews with DC members as both a platform for signaling/socializing change as well as to gather intelligence about the DLP, **creating the DLP!!**) and your struggles (figuring out how to manage change and communicate the need for its management to software engineers comes to mind).

Right now, the deck is general, distant: bring it closer to the work the people in the CX CoP are doing, and closer to the work you're doing. Keep some of the high level stuff, like slides 6, 8-10, 13, and 14, but make space for your story. People will reach out for more training for the abstract stuff, but telling your story will help them see themselves and their work through the lens of Change Management.

**Comment by monicas-d** [comment]
Completed successfully! :) Thanks for all your support!
