### ISSUE TITLE
Evaluation - gsaauctions.gov

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#282]
Website Evaluation of gsaauctions.gov - Drand Dixon
**To Do**
- [x] Set appointment 8/22  1:30 to 2:00 
- [x] assigned people @RachelF and @hatfieldjm4 
**Progress**
- [ ] Scan
- [ ] [interview notes](https://docs.google.com/document/d/1vGKvUDQUF5_iRN8BrYt8K3fOdd-QIR48cQtnoxjiEp0/edit?usp=sharing)
- [ ] [Interview Spreadsheet](https://docs.google.com/spreadsheets/d/1IOPChDWYFmpTYU20PieUtUp_o6yzngkfkn9szroJYc8/edit?usp=sharing)
**Rec Docs Needed**
- [ ] Summary
- [ ] Tl:Dr
- [ ] immediate action
**Done** 
- [ ] recc link

**Comment by hatfieldjm4** [comment]
The initial HCD interview was with Drand Dixon, but he is no longer on the gsaauctions.gov team. He pointed us to Karen Warrior, who leads a "zone" of the site, but not the national program. She directed us to Matt Manger and Angel Paschall-Harmon for the national program to determine a website manager. Matt indicated that Lloyd Aucoin is the "website manager" from the perspective of USWDS. This sounds more like a technical lead on the site rather than a website manager, though.
