### ISSUE TITLE
DC - disposal.gsa.gov

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#332]
## Website URL

disposal.gsa.gov/s/property
existing version >> https://pddv22dvn-disposal.cs32.force.com/s/property/a0Xr0000002zKLfEAM/test-prop-22

## Checklist

List below the specific actions to be taken

- [ ] Schedule initial call with team to learn their goals but also conduct an informal [Website Evaluation](https://docs.google.com/document/d/1IFkJT_yYSd2Nwmjf-7PK7P96dE6hbyqisH4NuAH3nkU/edit?disco=AAAAWEabv74)
- [ ] Create new folder within existing website folder in drive called "Design Consult" and place Eval and other contents there.
  - {folder link goes here}

### Establish Recommendations

- [ ] Depending on the state of the site, pull down current HTML locally so as to have a static version on the desktop. Create a copy of the files which will hold any proposed changes. Once complete, run `git diff` against both html files and upload all contents to Drive in a Zip file.

```sh
# insert website name in between quotes, run commands one after the other. Assumes folder is the domain name
WEBSITE_NAME="blah.gov"
zip $WEBSITE_NAME.zip $WEBSITE_NAME -r -x $WEBSITE_NAME/notes.md -x $WEBSITE_NAME/.DS_Store
```

  - [ ] Capture screenshots of our proposed changes (desktop and mobile)
- [ ] Present findings and recommendations to team. This should come in the form of a meeting, a with a written report. The tone of the report should be actionable and speak to the changes suggested. If providing an updated HTML file, be sure to speak to those changes at a high level (do not go line by line). The [apps.ocfo.gsa.gov Changes and Recommendations](https://docs.google.com/document/d/1eXwkolQ6-dR8NvzBlD-_ALPMrz2GfwlrkNX6KVOxFDI/edit) is a good example.

### Post Deployment

_Following the change in production, take the following actions:_

- [ ] Copy "[before/after deck](https://docs.google.com/presentation/d/1Z4H6YF9SJqOpnetYGDJkv_52PjtbV6bcGZ_AOU7dhag/edit)" template, insert screenshots, update content within brackets {}
  - {link to deck goes here}
  - [ ] Symlink the deck into the website folder used for evals. In Drive, click the deck, press `Shift + Z` and select the website eval folder for that property.
- 🎥 [Meeting Recording](https://drive.google.com/file/d/1rM-k85ut90py3_J3fLWpFzwEkH9HgmQE/view)

**Comment by AKM399** [comment]
@anatecture @mvogelgesang did this meet happen?  move to in progress?

**Comment by mvogelgesang** [comment]
@AKM399 meeting with the team today at 1:30 ET

**Comment by anatecture** [comment]
@mvogelgesang and I met w/ the team today. Here's a write up of our reccs: 

1. Use horizontal rules or shading instead of outline boxes
2. Clarified that within the header and footer they can change any styling element they want
3. Increase line heights to make more visible 
4. Flipped to mobile to show how contact information and pictures shrunk and got crowded; recommended that they stack these elements on mobile 
5. Increase header size and make them consistent 
6. Maybe consider using different fonts for headers and body copy. 
7. Links need to just be accessible links; get rid of direction to "click here" 

Links we put in the chat: 
You10:38 AM
here are the colors you can use: https://designsystem.digital.gov/utilities/color/
You10:44 AM
https://designsystem.digital.gov/components/side-navigation/
here's the side navigation component
You10:47 AM
header component: https://designsystem.digital.gov/components/header/

**Comment by anatecture** [comment]
[Mock](https://docs.google.com/drawings/d/1LMy-DODn3uOn-7IVfQyd4MrKkI0gNsGX5Ll33JHsVJE/edit) from @mvogelgesang's desk
