### ISSUE TITLE
sprint 3 - backlog examination

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#359]
Sprint 3 adjustments - looking at resources and backlogs

Begin the process of looking at resources utilized in web teams as a part of evaluation process.

Discussion topics:

How a categorization of websites with  remediation needs might inform the work -
Websites are  lacking these things because they ....lack the resource, lack the speciality, lack the knowledge...etc.

## Checklist

- [ ] work request for backlog link into interview
- [ ] categorize  backlog issues by type
- [ ] clarify support by resource condition (lacking resources, lacking knowledge, lacking attention) and area of need (content, USWDS, accessibility...)

**Comment by AKM399** [comment]
@RachelF @mvogelgesang @hatfieldjm4 
follow up to yesterdays discussion

**Comment by AKM399** [comment]
@ryanwoldatwork for review and feedback

**Comment by ryanwoldatwork** [comment]
Websites are Products.
Each Product should have a Backlog.

The existence and presence of a Backlog provides a shared document used to account for work to be done (or not to be done).

1. Ensure that the work that needs to be done (however that is defined) is reflected in the Backlog. Accessibility, USWDS, etc.
2. Tag the work by generic type of resource (for example: dev/design/pm/data)
3. Prioritize the work by 1. business value and 2. effort on a 2x2

I'd drop the "lack of" framing.
The not-done work made visible makes the debt and "lack" explicit enough.

Moreso, enable a positive framing for work that can and needs to be done. HTML updating because Accessibility, USWDS, content refactoring, etc.

The work should be obvious and visible.

**Comment by mvogelgesang** [comment]
team is incorporating changes into web evals v2 AND webmod group led by @ryanwoldatwork
