### ISSUE TITLE
Case Studies - website best practices

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#413]
## Summary

We have heard from a number of teams who have taken unique steps to gather user input, test content, promote accessibility/ equity, etc. We should produce a playbook of these plays and highlight the teams doing great work. 

## Additional context and links

Some initial topics/ teams for consideration

- citizenscience.gov - stakeholder workshop with their Community of Practice
- cdo.gov - Taking accessibility to the next level by considering equity as a part of their engagement. 

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by AKM399** [comment]
self contained - but stitches together in  a compilation.

**Comment by monicas-d** [comment]
Is this what the new intern, Lila, is doing? She said she's working on case studies, but not sure what that means in terms of client outreach to whom, when, etc. We all need to coordinate with her as to whom and the messaging for consistency/change efforts. Thanks!

**Comment by RachelF** [comment]
@monicas-d,  @lilaconlee is working on case studies that we plan to publish as part of the CX Guide (https://github.com/GSA/EDX/issues/456). I don't think she's actually talked to anyone yet, but I'm sure she can provide an update to make sure we stay in sync.

**Comment by lilaconlee** [comment]
@monicas-d  I've only scheduled conversations within the OCE team, I'll make sure to coordinate before scheduling externally!

**Comment by anatecture** [comment]
@lilaconlee's work is scoped to gather stories of past OCE projects, so it should not intersect with these ongoing conversations. That being said, if there's any questions on whether an outside OCE partner might be included in the groups we're talking with on this work, we'll definitely coordinate prior to Lila's meetings.

**Comment by monicas-d** [comment]
Great to know, thanks! Because she's on the EDX team, Gail and I presumed
it was on EDX projects and not past OCE projects.


-- 

U.S. General Services Administration

*Monica Suber-Duffy*, Federal Internal Coach
<https://insite.gsa.gov/topics/training-and-development/developmental-services/coaching-services>

Organizational Development Consultant
<https://insite.gsa.gov/topics/training-and-development/developmental-services/organizational-development>

GSA  | OHRM Talent Development

Pronouns: She/Her/Hers

Office of Human Resources Management (OHRM)

1800 F St, NW

Washington, DC 20526

Mobile: (202) 701-8197

E-mail: ***@***.***

Join the Yoga & Mindfulness Chatter Group
<https://gsa.my.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9t0000000aU0i>,
and see our page on InSite
<https://insite.gsa.gov/topics/training-and-development/continuous-learning/yoga-mindfulness>

Between stimulus and response there is a space. In that space is our power
to choose our response. In that response lies our growth and our
freedom.-Viktor
E. Frankl

<https://insite.gsa.gov/topics/hr-pay-and-leave>

**Comment by AKM399** [comment]
We need a process around capturing best practices from evals.

**Comment by AKM399** [comment]
addressed in service category work and compilation document projects.  @AKM399 to document the tie into the compilation document.
