### ISSUE TITLE
How might we keep the list of website managers up to date?

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#474]
## Summary

What is the best way to maintain the list of website managers and keep the information in Touchpoints up to date?

## Key data sets

- Current months GSA roster
- Previous months GSA roster
- Website list from Touchpoints

## Outputs

List of websites where:
- Manager has left the agency
- Manager has changed position, PD#, department/office, series, grade

That list should be produced on XX interval and result in a GitHub issue that describes specific actions to be taken.

**Comment by monicas-d** [comment]
Here are my notes from our GitHub Cleaning email. Please revise if I got anything wrong. Thanks!

Where do we keep the most up-to-date list of website manager?

- Touchpoints for outward facing

Who updates it and when? (ACTION: discuss with team)

- Website manager

Touchpoints:	

- Monica shared in (6/21/22 GitHub Cleaning meeting): we should get Ryan Wold to update the two categories for POCs, define it, and ask website managers to update it
- Mark started a GitHub for this task: https://github.com/GSA/EDX/issues/474 

Who should be the secondary point of contact?

- Aaron (6/21/22 GitHub Cleaning meeting): Supervisors should be since if the site manager leaves, we go to them to find out who replaces them

**Comment by AKM399** [comment]
@gailsprinkle recently spoke with @patriciacheng about working on this but needs a permanent OCE manager maintaining it

**Comment by AKM399** [comment]
HR is supportive of the idea.  Wants to triangulate with digital registry.  Needs more information but it doesn't have to be visible in registry.

**Comment by AKM399** [comment]
Relational database is needed.  Airtable could be the answer but there have been ATO issues in the past.  Issue was originally created to add fields and bring them over.   worth a new ticket - @mvogelgesang

**Comment by AKM399** [comment]
we need an easier way to capture monthly changes.

**Comment by AKM399** [comment]
key question - how often is change control needed?

**Comment by AKM399** [comment]
closed in favor of previous issue on website manager lists
