### ISSUE TITLE
"Staging" status is used in Touchpoints but unavailable in the dropdown menu when editing a website entry

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#482]
As a user of the website inventory on Touchpoints, I want to be able to denote the sites that are staging sites rather than production sites. The "in_development" status may be used but will confuse users about the lifecycle flow of websites (i.e. created, approved, in_development, etc.). 

Currently 13 sites have "staging" as a status in the Touchpoints website inventory, but the "staging" option does not appear in the dropdown menu when editing a website. There are 14 sites that have "staging" in their domain name but have a status of either "in_development" or "production", which is not an accurate depiction of the site.

**Comment by ryanwoldatwork** [comment]
Hi @hatfieldjm4, an upcoming update will address this.

**Comment by hatfieldjm4** [comment]
Thank you, @ryanwoldatwork !

**Comment by ryanwoldatwork** [comment]
@hatfieldjm4,

Each stateful process transition for Websites now has a button to execute the action.

A user can now click "Stage" the site, instead of "Edit" then go the the "status" dropdown and select "Staging" as a state.


![111](https://user-images.githubusercontent.com/64987852/178357961-032739e6-ea73-4dfe-9169-6b9188a6acbf.png)

This screenshot shows the Website with a `staging` status, as well as a modal window outlining the different states.

![222](https://user-images.githubusercontent.com/64987852/178357978-8dffda07-5ac2-4289-adaf-0ac8f834608f.png)

**Comment by hatfieldjm4** [comment]
Great, I was able to edit a few sites that were listed as "production" but had "staging" in their domain name. Thanks very much, @ryanwoldatwork !
