### ISSUE TITLE
Updating Design Consults to USWDS v3; creating new Consults for teams

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#500]
## Summary

In this course of this sprint, @lilaconlee and @mvogelgesang will update the EDX Design Consults page to USWDS v3, briefly noting where the System's tutorials need tweaking in order to better guide users through. 

After that update, @lilaconlee will implement the USWDS header, footer, banner, identifier on a few sites that need it. Our goals  in this project, in order of priority, are to: 

1. Show GSA teams the art of the possible in terms of implementing the USWDS. 
2. Show GSA and other leadership that implementing the USWDS is non-trivial, esp on sites that have been online for a while  
3. Build a "This Broke When We Tried to Implement" site list. This list will show sites that are so old that they _cannot_ implement USWDS, which will be helpful information in decisions around migration, sunset, and maintenance for the sites. 
4. Show the USWDS team that implementing on legacy sites will be a core problem for web teams- do they want to engage in that problem?

Sites we might consider starting with once the Design Consult framework is running on v3: 

- computersforlearning.gov
- cpars.gov

@mvogelgesang @lilaconlee will go through the Website Inventory to find ~7 total sites to redesign.

**Comment by mvogelgesang** [comment]
@lilaconlee has been at work implementing Astro and porting Design Consults to it. Per our conversation yesterday, there are a number of reasons to take a slim-lined approach. The Design Consults site is a vanilla implementation of USWDS (that is to say no theme customizations). As a result, importing and actively compiling SASS is less a priority for us than it might be for other teams. Additionally, the need to tree-shake resources and optimize the build are less a priority for Design Consults due to its size and the amount of traffic it receives. For this reason, a direct import of the CSS from `@uswds/uswds/dist/css/` does the trick for our Astro implementation.

For teams that require customizations to a theme settings file, going with the Gulp or USWDS Compile workflow will be necessary.


When it comes to Jekyll, the USWDS website (designsystem.digital.gov) runs on the framework and has migrated to USWDS v3.0. This is to say there is a path to migrate existing Jekyll sites using v2.x to v3.x. 

@anatecture ^^^

**Comment by lilaconlee** [comment]
Progress update
- Added first pass of drivethru.gsa.gov to design consults site in #539 
- Switched to focusing on [Figma mock-ups](https://www.figma.com/file/TRrNJ7AV5xJtIdMf9sKvFr/Untitled?node-id=0%3A1) 

On Figma
- Complete: drivethru.gsa.gov
-  In progress: ask.gsa.gov is in progress
- Queued: computersforlearning.gov, gsaxcess.gov, usmcservmart.gsa.gov
