### ISSUE TITLE
Create data transparency and replicability for website eval

### ISSUE THREAD

**Issue by anatecture** [GSA/EDX#506]
## Summary

Get statuscard published; get website eval criteria into official policy

**Comment by mvogelgesang** [comment]
What is Project: To establish a centralized home for website evaluations and related data so as to provide informed feedback to website teams and demonstrate the relationship between sites.

Why is the Project: Many websites today are an extension of the office of the creators rather than an expression of the overall service area (e.g. travel). This project aims to highlight the service area(s) of a given site as well as providing feedback to website managers and their development teams to increase compliance and adherence to GSA standards. 

How the Project:

**Comment by AKM399** [comment]
waiting for gear 3 launch

**Comment by AKM399** [comment]
complete
