### ISSUE TITLE
EDX Elevator Speech Draft

### ISSUE THREAD

**Issue by monicas-d** [GSA/EDX#89]
https://docs.google.com/document/d/1MxWEDD4kelqfhJnuQ0Ku8tsio9aSRTv5d2PBGueo21o/edit

We want to make sure this makes sense to you all, and we use it consistently in our messaging in writing and verbally. Thanks!

Please @RachelF @anatecture @ryanwoldatwork @AKM399 @hatfieldjm4

**Comment by monicas-d** [comment]
This is final from Rachel, Gail, and my point of view. If you feel otherwise, let us know here and then we will close. Thanks!

**Brief Overview to use in Written Communication**
GSA employees are passionate about building great digital experiences; however, this enthusiasm has resulted in a proliferation of websites, systems, and services that cause confusion and frustration for customers, instead of clarity and satisfaction. With support from  senior leaders on GSA’s Executive Board, the Office of Customer Experience now houses an Enterprise Digital Experience (EDX) Team to address this challenge as stewards, not owners, of our digital properties. Since its inception in January 2021, EDX has worked alongside the GSA Digital Council to deliver governance, service, and product designs that provide a more consistent and helpful experience to GSA customers.

***

**Elevator Speech**
GSA has an overabundance of websites which causes confusion for our customers. The Enterprise Digital Experience team in the Office of Customer Experience works with GSA’ Digital Council to tackle this challenge and improve how people interact with GSA online.
We’re reaching out to you because [insert customized “ask” for each key stakeholder engagement].

**Comment by ryanwoldatwork** [comment]
@monicas-d, thanks!

Where would you like this text to live online?

**Comment by patriciacheng** [comment]
I would suggest editing "enthusiasm" and replacing it with something like "lack of governance".  We're not saying enthusiasm is bad.  I believe we're trying to say enthusiasm needs to be balanced by proper governance / coordination / planning / whatever the right word is.

**Comment by RachelF** [comment]
After sleeping on it, and then thinking about Patricia's comment, I'd like to suggest a revision. I realized we hadn't specifically called out "content" and that's a big problem that we need to tackle. (It's also 12 words shorter.) 

GSA employees are passionate about building great digital experiences, which has resulted in a proliferation of websites, content, systems, and services that cause confusion and frustration for customers. With support from senior leaders on GSA’s Executive Board, the Office of Customer Experience houses an Enterprise Digital Experience (EDX) Team to address this challenge. Since its inception in January 2021, EDX has worked alongside the GSA Digital Council to improve management and governance of GSA's digital properties, and deliver a more consistent, clear, and helpful experience to our customers.

@ryanwoldatwork would it make sense to publish the final version on https://github.com/GSA/EDX/blob/main/README.md?

**Comment by RachelF** [comment]
@monicas-d and @gailsprinkle OK'd the revised language so I'm re-closing this now :)

**Comment by monicas-d** [comment]
Updated and closing. Thanks for your suggestions!
