### ISSUE TITLE
Get feedback on Digital Council meetings

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#93]
* [x] @monicas-d: create the Survey in Google Forms based on this issue
* [ ] @RachelF: to socialize the idea about feedback forms after meetings for the Digital Council
* [ ] Rachel to Survey the Digital Council members in December
* [ ] Next co-chair reads the feedback and does something about it

**Comment by monicas-d** [comment]
@RachelF Is this something we want to start doing in Calendar Year 2022? Thanks.

**Comment by monicas-d** [comment]
Hey @RachelF , did you get feedback in December, and then Peter read them out? I don't think it happened but may want to consider it...also, since EB meetings are monthly, you may want to consider surveying the SESers by way of multiple choice questions in poll format in Google and record them via Snipping tool for review later...thoughts? What I have learned over the years is that SESers do not have the time to complete evals unless it's live in a session.

**Comment by RachelF** [comment]
We asked Board members for feedback after the November meeting and did not get one single response :(
We haven't asked council members yet but we should.

**Comment by monicas-d** [comment]
Right - thus why I recommend using the polls during the session so you get that feedback live; otherwise, you won't get what you need. Let me know how I can help! Thanks.

**Comment by ryanwoldatwork** [comment]
Not getting feedback is also feedback.

**Comment by anatecture** [comment]
agree w/ @ryanwoldatwork. @RachelF you asked and they didn't respond. you're trying new programming, including round robin and team presentations. we'll see how it goes, but you did get feedback in the form of silence.
